$schema: ./schema.json
# Native
App:
  Landscape: pichu
  EnableSwagger: true
  GenerateConfig: false
Swagger:
  Title: Pichu Sulfone Zinc API
# OTEL
Logs:
  Exporter:
    Console:
      Enabled: false
    Otlp:
      Enabled: true
Trace:
  Exporter:
    Otlp:
      Enabled: true

Metrics:
  Exporter:
    Otlp:
      Enabled: true

# Infra-based
Database:
  Main: {}
Cache: {}
BlockStorage: {}
# external
HttpClient: {}
