version: "3"

vars:
  CHART_PATH: infra/root_chart
  RELEASE_NAME: carboxylicacid-carbon

includes:
  helm: Taskfile.helm.yml
  tear: tasks/Taskfile.tear.yml
  stop: tasks/Taskfile.stop.yml

tasks:
  setup:
    desc: Setups dotnet
    cmds:
      - dotnet restore --use-lock-file
      - dotnet tool restore
  build:
    desc: Builds application
    cmds:
      - dotnet build --no-restore
  tear:
    desc: Tears down the local development cluster
    cmds:
      - ./scripts/local/delete-k3d-cluster.sh
  dev:
    desc: Starts developing application
    cmds:
      - ./scripts/local/dev.sh ./config/dev.yaml dotnet watch run --project App
  stop:
    desc: Stops development in tilt
    cmds:
      - tilt down
