version: 3

tasks:
  sync:
    desc: Sync configuration
    cmds:
      - ./scripts/local/config-sync.sh
  update:
    desc: Install dependencies
    cmds:
      - helm dependency update ./infra/root_chart
  build:
    desc: Build dependencies
    cmds:
      - helm dependency build ./infra/root_chart
  remove:
    desc: Removes the chart
    cmds:
      - helm uninstall {{.RELEASE}}
  install:
    desc: Installs the chart
    deps:
      - sync
      - dep
    cmds:
      - >-
        helm upgrade --install  {{.RELEASE}} ./infra/root_chart
        --values ./infra/root_chart/values.yaml
        --values ./infra/root_chart/values{{.LANDSCAPE}}.yaml
  template:
    desc: Templates the chart
    deps:
      - sync
      - update
    cmds:
      - >-
        helm template {{.RELEASE}} ./infra/root_chart
        --values ./infra/root_chart/values.yaml
        --values ./infra/root_chart/values{{.LANDSCAPE}}.yaml
  debug:
    desc: Debugs the chart
    deps:
      - sync
      - update
    cmds:
      - >-
        helm template --debug {{.RELEASE}} ./infra/root_chart
        --values ./infra/root_chart/values.yaml
        --values ./infra/root_chart/values{{.LANDSCAPE}}.yaml
