version: '3'

tasks:
  default:
    desc: Stop all everything
    cmds:
      - task: stop:dev
      - task: stop:test
  dev:
    desc: Stop the development workflow
    cmds:
      - tilt down
  test:
    desc: Stop the test workflow
    cmds:
      - tilt down -- --config config/test.yaml --action test
