{{-  range $k, $v := .Values.ingress.tls -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "dotnet-chart.fullname-with-suffix" (dict "arg" $v.secretName "root" $) }}
  labels: {{- include "dotnet-chart.labels" $ | nindent 4 }}
  annotations: {{- include "dotnet-chart.annotations" $ | nindent 4 }}
spec:
  secretName: {{ include "dotnet-chart.fullname-with-suffix" (dict "arg" $v.secretName "root" $) }}
  issuerRef:
    name: {{ $v.issuerRef }}
    kind: ClusterIssuer
  dnsNames:
    {{- range $hk, $hv := $v.hosts }}
    - {{ $hv }}
    {{- end }}
---
{{- end -}}
