apiVersion: v1
kind: Service
metadata:
  name: {{ include "dotnet-chart.fullname" . }}
  labels: {{- include "dotnet-chart.labels" . | nindent 4 }}
  annotations: {{- include "dotnet-chart.annotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "dotnet-chart.selectorLabels" . | nindent 4 }}
