{{- if .Values.bromine.enable }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "root-chart.fullname-with-suffix" (dict "arg" .Values.bromine.target "root" .) }}
  labels: {{- include "root-chart.labels" . | nindent 4 }}
  annotations: {{- include "root-chart.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ .Values.bromine.storeName }}

  target:
    name: {{ .Values.bromine.target }}

  dataFrom:
    - find:
        name:
          regexp: .*
  {{- end }}