apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dotnet-migration.fullname-with-suffix" (dict "arg" "config" "root" .) }}
  labels: {{- include "dotnet-migration.labels" . | nindent 4 }}
  annotations: {{- include "dotnet-migration.annotations" . | nindent 4 }}
data:
  settings.yaml: |
    {{- $pathBase := printf "%ssettings.yaml" "app/" -}}
    {{- $fileContentBase := .Files.Get $pathBase -}}
    {{- $configBase := fromYaml $fileContentBase -}}
    {{- $finalBase := merge .Values.appSettings $configBase -}}
    {{- toYaml $finalBase | nindent 4 }}
  settings.{{ .Values.serviceTree.landscape }}.yaml: |
    {{- $path := printf "%ssettings.%s.yaml" "app/" .Values.serviceTree.landscape -}}
    {{- $fileContent := .Files.Get $path -}}
    {{- $config := fromYaml $fileContent -}}
    {{- $final := merge .Values.appSettings $config -}}
    {{- toYaml $final | nindent 4 }}
