apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dotnet-migration.fullname-with-suffix" (dict "arg" "config" "root" .) }}
  labels: {{- include "dotnet-migration.labels" . | nindent 4 }}
  annotations: {{- include "dotnet-migration.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
data:
  settings.{{ .Values.serviceTree.landscape }}.yaml: |
    {{- $path := printf "%ssettings.%s.yaml" "app/" .Values.serviceTree.landscape -}}
    {{- $fileContent := .Files.Get $path -}}
    {{- $config := fromYaml $fileContent -}}
    {{- $final := merge .Values.appSettings $config -}}
    {{- toYaml $final | nindent 4 }}
