serviceTree:
  landscape: &landscape tauros

api:
  enabled: true
  serviceTree:
    landscape: *landscape

  imagePullSecrets: []

  replicaCount: 1

  configMountPath: /app/Config

  service:
    type: ClusterIP
    port: 80
    containerPort: 9030

  ingress:
    enabled: true
    className: traefik
    hosts:
      - host: api.zinc.sulfone.tauros.lvh.me
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

migration:
  enabled: true
  serviceTree:
    landscape: *landscape

maindb:
  enable: true
