landscape: &landscape lapras

api:
  enabled: true
  sericeTree:
    landscape: *landscape

  imagePullSecrets: []

  replicaCount: 1

  configMountPath: /app/App/Config/settings.yaml

  service:
    type: ClusterIP
    port: 80
    containerPort: 9001

  ingress:
    enabled: true
    ingressClass: traefik
    hosts:
      - host: api.carbon.carboxylicacid.lapras.lvh.me
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

migration:
  enabled: false

maincache:
  enable: true

altcache:
  enable: true

maindb:
  enable: true

mainstorage:
  enable: true
