serviceTree: &serviceTree
  landscape: lapras
  platform: sulfone
  service: zinc
  layer: "2"

bromine:
  enable: false
  # -- Store name to create
  storeName: sulfone-zinc
  # -- Secret of Secrets reference
  rootSecret:
    # -- DOPPLER Token Reference
    ref: "SULFONE_ZINC"

api:
  enabled: true

  nameOverride: "api"
  fullnameOverride: ""

  serviceTree:
    <<: *serviceTree
    module: api

  imagePullSecrets: []

  replicaCount: 1

  appSettings:
    App:
      Mode: Server

  configMountPath: /app/Config

  image:
    repository: sulfone-zinc-api
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 80
    containerPort: 9000

  ingress:
    enabled: true
    ingressClass: traefik
    hosts:
      - host: api.zinc.sulfone.lapras.lvh.me
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: sample
        issuerRef: sample
        hosts:
          - api.zinc.sulfone.lapras.lvh.me

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling: {}
  readinessProbe:
    httpGet:
      path: /
      port: http
      initialDelaySeconds: 5

  livenessProbe:
    httpGet:
      path: /
      port: http
      initialDelaySeconds: 5

  nodeSelector: {}

  tolerations: []

  affinity: {}

  topologySpreadConstraints: {}

migration:
  enabled: false

  nameOverride: "migration"
  fullnameOverride: ""

  serviceTree:
    <<: *serviceTree
    module: migration
  aspNetEnv: Development

  appSettings:
    App:
      Mode: Migration

  backoffLimit: 4
  configMountPath: /app/Config

  image:
    repository: sulfone-zinc-migration
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""

  imagePullSecrets: []

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1Gi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  topologySpreadConstraints: {}

maindb:
  nameOverride: main-database
  primary:
    persistence:
      enabled: false
  auth:
    database: sulfone-zinc
    username: admin
    password: supersecret
