serviceTree:
  landscape: &landscape pichu

bromine:
  enable: true

  target: &target "sulfone-zinc"

api:
  enabled: true
  envFromSecret: *target
  sericeTree:
    landscape: *landscape
  image:
    repository: ghcr.io/atomicloud/sulfone.zinc/api-amd
  imagePullSecrets: []

  replicaCount: 1

  configMountPath: /app/Config

  service:
    type: ClusterIP
    port: 80
    containerPort: 9050

  ingress:
    enabled: true
    ingressClass: nginx
    annotations:
      cert-manager.io/cluster-issuer: "entei-zinc-letsencrypt-issuer"
    hosts:
      - host: api.zinc.sulfone.pichu.cluster.atomi.cloud
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - hosts:
          - api.zinc.sulfone.pichu.cluster.atomi.cloud
        secretName: api-zinc-sulfone-cloud-tls

migration:
  enabled: true
  envFromSecret: *target
  image:
    repository: ghcr.io/atomicloud/sulfone.zinc/api-amd
  serviceTree:
    landscape: *landscape

maindb:
  enable: false
