serviceTree:
  landscape: lapras
  platform: sulfone
  service: dotnet
  module: api

replicaCount: 1

aspNetEnv: Development

appSettings:
  App:
    Mode: Server

configMountPath: /app/App/Config

image:
  repository: dotnet-chart
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  containerPort: 9000

ingress:
  enabled: false
  className: "traefik"
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}

autoscaling: {}

readinessProbe: {}

livenessProbe: {}

nodeSelector: {}

tolerations: []

affinity: {}

topologySpreadConstraints: {}
