name: CD

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-app:
    name: Build API Image
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: zinc

      dockerfile: ./infra/Dockerfile
      image_name: api

      version: ${{ github.ref_name }}
  build-migrate:
    name: Build Migration Image
    uses: ./.github/workflows/⚡reusable-docker.yaml
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: zinc

      dockerfile: ./infra/migrate.Dockerfile
      image_name: migrate

      version: ${{ github.ref_name }}
  helm:
    name: Helm Chart
    uses: ./.github/workflows/⚡reusable-helm.yaml
    secrets: inherit
    with:
      atomi_platform: sulfone
      atomi_service: zinc
      chart_path: ./infra/root_chart

      version: ${{ github.ref_name }}
